### ISSUE TITLE
Cannot use hadoop-pcap-lib with Hadoop 1.2.1

### ISSUE THREAD

**Issue by rahulagr** [RIPE-NCC/hadoop-pcap#18]
Hi,

I am trying to use hadoop-pcap-lib with Hadoop 1.2.1. I am writing a driver, but driver expects the argument to setInputFormatClass a class extending mapreducer.FileInputFormat instead of mapred.FileInputFormat. Do you have any latest version of PcapInputFormat.java?

Thanks
Rahul

**Comment by wnagele** [comment]
This should be fixed by #22.
