### ISSUE TITLE
Can not read the ts_usec field

### ISSUE THREAD

**Issue by zihu** [RIPE-NCC/hadoop-pcap#19]
I am having some issues to read the ts_usec field from the hive table.  I am doing exactly the same steps as listed in the example: https://github.com/RIPE-NCC/hadoop-pcap/tree/master/hadoop-pcap-serde.
And I tried the latest release "hadoop-pcap-serde-1.0-jar-with-dependencies.jar", with latest Hadoop 2.4.1 and Hive 0.13.1, but still no luck.  

The error message is:
hive (default)> select * from pcaps limit 10;
OK
pcaps.ts	pcaps.ts_usec	pcaps.protocol	pcaps.src	pcaps.src_port	pcaps.dst	pcaps.dst_port	pcaps.len	pcaps.ttl	pcaps.dns_queryid	pcaps.dns_flags pcaps.dns_opcode	pcaps.dns_rcode	pcaps.dns_question	pcaps.dns_answer	pcaps.dns_authority	pcaps.dns_additional
Failed with exception java.io.IOException:org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.ClassCastException: java.math.BigDecimal cannot be cast to org.apache.hadoop.hive.common.type.HiveDecimal

From the error message, it looks like that the convert from jave BigDecimal to HiveDecimal failed, but I am not sure how to fix it.

**Comment by mageru** [comment]
I was able to resolve this issue by editing
hadoop-pcap-lib/src/main/java/net/ripe/hadoop/pcap/PcapReader.java
and changing
packet.put(Packet.TS_USEC, packetTimestampUsec);
to
packet.put(Packet.TS_USEC, packetTimestampUsec.longValue());

And modifying my create table statement 
changing: ts_usec data type to bigint
ts_usec bigint,

**Comment by mageru** [comment]
I have forked and fixed the project here if you are still looking to run it. 

https://github.com/mageru/hadoop-pcap

**Comment by wnagele** [comment]
This should be fixed in #22.
