### ISSUE TITLE
New fields addition

### ISSUE THREAD

**Issue by raghuveerm** [RIPE-NCC/hadoop-pcap#20]
I did not see any help on how to extract fields from the binary files. For example i want to extract bytes_transferred for each packet in the ndttrace files but any change i do is not reflecting in the code. Kindly suggest.

**Comment by wnagele** [comment]
This library reads PCAP files, not NDT trace files.

**Comment by raghuveerm** [comment]
I think ndttrace files have PCAP format data as well. Yes i agree that ndttrace files cannot be read completely by this lib.
