### ISSUE TITLE
Re-compile to include HiveDecimal

### ISSUE THREAD

**Issue by grues** [RIPE-NCC/hadoop-pcap#21]
Hi All,
I downloaded the Serde and installed on a Cloudera Disto of Hadoop version 5 and got the following error:  [Hive] java.math.BigDecimal cannot be cast to org.apache.hadoop.hive.common.type.HiveDecimal. 

This led to attempts a recompiling but I'm lacking package org.apache.hadoop.hive.common.type and others. 

Reference and back ground postings over at Google user group for Cloudera and Hive:
https://groups.google.com/a/cloudera.org/forum/#!topic/cdh-user/Qlc1hfo51cg

Regards

**Comment by mageru** [comment]
I have forked and fixed the project here if you are looking to run it. 
https://github.com/mageru/hadoop-pcap

**Comment by wnagele** [comment]
This should be fixed by #22.
