### ISSUE TITLE
headerKeys in HttpPcapReader not initialize properly

### ISSUE THREAD

**Issue by yiming187** [RIPE-NCC/hadoop-pcap#23]
Line 122 to 129
	private void propagateHeaders(HttpPacket packet, Header[] headers) {
		LinkedList<String> headerKeys = new LinkedList<String>();
		for (Header header : headers) {
			String headerKey = HEADER_PREFIX + header.getName().toLowerCase();
			packet.put(headerKey, header.getValue());
		}
		packet.put(HttpPacket.HTTP_HEADERS, Joiner.on(',').join(headerKeys));
	}

headerKeys is initialized, but never be populated with any value.

**Comment by wnagele** [comment]
Well spotted - fix applied.
