### ISSUE TITLE
parsed pcaket with NULL source and destination

### ISSUE THREAD

**Issue by mfaisal** [RIPE-NCC/hadoop-pcap#25]
Hi all,

Using the latest jar, I tried to get the pcaket properties like src, dst, ts, etc. for 160 pcap files. I tried with PcapReader. However, I found lot of packets have src, dst, protocol, src_port, dst_port, etc. with NULL value.

I am not sure whether it is a bug or it can be happen for PCAP? 

Is there any documentation for this 'hadoop-pcap'? or any diagragram for process flow for pcaps?

Thanks,
Mustafa

**Comment by wnagele** [comment]
Please provide an example PCAP so we can check this.

**Comment by mfaisal** [comment]
Each file is about 1GB (968 MB). Is there any way I can upload a file?

**Comment by wnagele** [comment]
Just extract some of the packets using tcpdump -r current.pcap -c <number_of_packets> -w new.pcap. You can then email it to me at mail@wnagele.com.
