### ISSUE TITLE
"Not a PCAP file" error

### ISSUE THREAD

**Issue by cupdike** [RIPE-NCC/hadoop-pcap#26]
I dump a file like this:
`sudo tcpdump -U -s 0 -w dump1.pcap`

When I try to use a DnsPcapReader on it, it throws the "Not a PCAP file (Couldn't find magic number)" error.

If I hexdump the file, I do see the magic number near the start: 
`00000000  0a 0d 0d 0a 94 00 00 00  4d 3c 2b 1a 01 00 00 00`

I tried skipping those first 8 bytes, and looking inside PcapReaderUtil, it looks like it is actually accessing the correct bytes to do the reverse evaluation (finding a1, b2, c3, d4)--but it still fails evaluation.  Any idea what I am doing wrong here?

**Comment by wnagele** [comment]
That looks like a PCAP-NG file. We don't have support for that just yet. Feel free to work and provide a pull request. :) You can use _editcap_ to convert your existing files back to PCAP format.

**Comment by cupdike** [comment]
Thanks for the pointer--and in case anyone else encounters this--apparently (at least on OSX), if you don't specify the interface when invoking tcpdump, it pulls from multiple interfaces and switches to PCAP-NG.  Just add the interface to the command line and the file will then be in PCAP.
