### ISSUE TITLE
new MapReduce API support would be nice

### ISSUE THREAD

**Issue by vicenteg** [RIPE-NCC/hadoop-pcap#32]
Hi,

I was glad to find this project, and had hoped to use it in some work I'm doing with spark. However once I got to spark streaming, I learned that the old MR API is not supported by spark streaming. So I hacked my way through porting the RecordReader and InputFormat to the new MR API, which makes it possible to use with Spark Streaming.

My fork is here: https://github.com/vicenteg/hadoop-pcap

The diff: https://github.com/RIPE-NCC/hadoop-pcap/compare/master...vicenteg:master

If this looks reasonable to you, I'll go ahead and submit the pull request.

Thanks for this project!

**Comment by wnagele** [comment]
Hey,

Thanks for contributing - this sounds like a good idea. Could you please change it to simply replace the old API. There is no need for us to carry the old API forward. Once you have it - send through a pull request so we can review it.

Cheers,
Wolfgang

**Comment by vicenteg** [comment]
Will do. Thanks.

**Comment by vicenteg** [comment]
Pull request #33 submitted.

**Comment by wnagele** [comment]
This has been merged.
